### ISSUE TITLE
Game should reset instead of refresh!

### ISSUE THREAD

**Issue by ashokdey** [phantomlabs/tic-tac-toe#2]
Currently, the **New Game** button is reloading the page which is not a suitable user experience, it needs to reset the game instead of reloading.

**Comment by TheSTL** [comment]
@ashokdey  I will be working on it

**Comment by TheSTL** [comment]
PR for this issue: https://github.com/phantomlabs/tic-tac-toe/pull/3

**Comment by ashokdey** [comment]
Closing as #3 fixes this issue. Thanks a lot @TheSTL
